- name : GNOME - Install Packages
  apt:
    state: latest
    pkg:
    - gnome-shell
    - ubuntu-gnome-desktop
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-weather
    - gnome-shell-extension-no-annoyance

- name: GNOME - Set GDM as default
  ansible.builtin.service:
    name: gdm
    state: started
    enabled: yes

- name: GNOME - Wayland QT BugFix
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    dest: "/home/{{ansible_env.SUDO_USER}}/.zshrc"
    line: export QT_QPA_PLATFORM=wayland
    owner: "{{ansible_env.SUDO_USER}}"

- name: GNOME - Configuration - Clock shown seconds
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-seconds"
    value: "true"
    state: present

- name: GNOME - Configuration - Clock shown weekday
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "true"
    state: present

- name: GNOME - Configuration - Theme Yary Dark
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Yaru-dark'"
    state: present

- name: GNOME - Configuration - Icon Theme Yaru
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Yaru'"
    state: present

- name: GNOME - Configuration - Cursor Theme Yaru
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/org/gnome/desktop/interface/cursor-theme"
    value: "'Yaru'"
    state: present

- name: GNOME - Configuration - Disable animations
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/org/gnome/desktop/interface/enable-animations"
    value: "false"
    state: present

- name: GNOME - Configuration - UI Font
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'Cantarell 11'"
    state: present

- name: GNOME - Configuration - Document Font
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/org/gnome/desktop/interface/document-font-name"
    value: "'Cantarell 11'"
    state: present

- name: GNOME - Configuration - Terminal Font
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    value: "'Ubuntu Mono derivative Powerline 8'"
    state: present

- name: GNOME - Nautilus - Icon Size
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/org/gnome/nautilus/icon-view/default-zoom-level"
    value: "'small'"
    state: present

- name: GNOME - Nautilus - Icon Size
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/org/gnome/nautilus/preferences/default-folder-viewer"
    value: "'icon-view'"
    state: present

- name: GNOME - Shell - Launcher
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['chromium_chromium.desktop', 'firefox.desktop', 'org.gnome.Nautilus.desktop', 'code_code.desktop', 'org.gnome.Calculator.desktop', 'com.gexperts.Tilix.desktop']"
    state: present

- name: GNOME - Shell - Extensions
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['ubuntu-appindicators@ubuntu.com', 'workspace-indicator@gnome-shell-extensions.gcampax.github.com']"
    state: present
