- name: PHP - Add Ondrej PPA
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: PHP - Install PHP8 CLI
  apt:
    state: latest
    pkg:
    - openssl
    - php8.0-cli
    - php8.0-curl
    - php8.0-mbstring
    - php8.0-mysql
    - php8.0-xml
    - php8.0-zip
    - php8.0-xdebug
    - php8.0-soap
    - php8.0-redis
    - php8.0-pgsql
    - php8.0-mongodb
    - php8.0-mcrypt
    - php8.0-ldap
    - php8.0-imagick
    - php8.0-gd
    - php-json
    - composer