- name: POWERLINE-FONTS - Check if installed
  become_user: "{{ansible_env.SUDO_USER}}"
  stat:
    path: ~/.fonts
  register: powerfonts_path


- name: POWERLINE-FONTS - Install fonts
  when: not powerfonts_path.stat.exists  
  ansible.builtin.script:
    cmd: /scripts/powerline-fonts.sh