- name : TILIX - Package Installation
  become: true
  apt:
    pkg:
      - tilix
      - python3-psutil
    state: latest

- name: TILIX - Set as default terminal emulator
  become: true
  command: "/usr/bin/update-alternatives --set x-terminal-emulator /usr/bin/tilix.wrapper"
  register: command_result
  changed_when: "command_result.stdout != ''"

- name: TILIX - ZSH configuration fix
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    dest: "/home/{{ansible_env.SUDO_USER}}/.zshrc"
    line: if [ $TILIX_ID ] || [ $VTE_VERSION ]; then source /etc/profile.d/vte-2.91.sh; fi
    owner: "{{ansible_env.SUDO_USER}}"

- name: TILIX - Option - Tabs on top
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/com/gexperts/Tilix/tab-position"
    value: "'top'"
    state: present

- name: TILIX - Option - Title Style
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/com/gexperts/Tilix/terminal-title-style"
    value: "'none'"
    state: present

- name: TILIX - Option - Dark Theme
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/com/gexperts/Tilix/theme-variant"
    value: "'dark'"
    state: present

- name: TILIX - Option - No toolbars
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/com/gexperts/Tilix/window-style"
    value: "'disable-csd-hide-toolbar'"
    state: present 

- name: TILIX - Default Profile - Find UUID
  become_user: "{{ansible_env.SUDO_USER}}"
  shell: gsettings get com.gexperts.Tilix.ProfilesList default | awk '{ print substr( $0, 2, length($0)-2 ) }'
  register: tilix_uuid_profile

- name: TILIX - Default Profile - Set Transparency
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/com/gexperts/Tilix/profiles/{{tilix_uuid_profile.stdout}}/background-transparency-percent"
    value: "10"
    state: present 

- name: TILIX - Default Profile - Set Transparency
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/com/gexperts/Tilix/profiles/{{tilix_uuid_profile.stdout}}/dim-transparency-percent"
    value: "10"
    state: present 

- name: TILIX - Default Profile - Set Transparency
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/com/gexperts/Tilix/profiles/{{tilix_uuid_profile.stdout}}/font"
    value: "'Ubuntu Mono derivative Powerline 13'"
    state: present 

- name: TILIX - Default Profile - Set Transparency
  become_user: "{{ansible_env.SUDO_USER}}"
  dconf:
    key: "/com/gexperts/Tilix/profiles/{{tilix_uuid_profile.stdout}}/use-system-font"
    value: "false"
    state: present 
